### ISSUE TITLE
cast Error

### ISSUE THREAD

**Issue by TomYOON** [TomYOON/pre_lol_project#3]
CastError: Cast to ObjectId failed for value "logout" at path "user" for model "Vote"
    at model.Query.exec (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/query.js:4358:21)
    at model.Query.Query.then (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/query.js:4450:15) {
  messageFormat: undefined,
  stringValue: '"logout"',
  kind: 'ObjectId',
  value: 'logout',
  path: 'user',
  reason: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
      at new ObjectID (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/bson/lib/bson/objectid.js:59:11)
      at castObjectId (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/cast/objectid.js:25:12)
      at ObjectId.cast (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/schema/objectid.js:279:12)
      at ObjectId.SchemaType.applySetters (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/schematype.js:1110:12)
      at ObjectId.SchemaType._castForQuery (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/schematype.js:1545:15)
      at ObjectId.SchemaType.castForQuery (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/schematype.js:1535:15)
      at ObjectId.SchemaType.castForQueryWrapper (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/schematype.js:1512:20)
      at cast (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/cast.js:331:32)
      at model.Query.Query.cast (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/query.js:4759:12)
      at model.Query.Query._castConditions (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/query.js:1841:10)
      at model.Query.<anonymous> (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/query.js:1868:8)
      at model.Query._wrappedThunk [as _find] (/Users/taesung/Documents/GitHub/pre_lol_project/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
      at /Users/taesung/Documents/GitHub/pre_lol_project/node_modules/kareem/index.js:370:33
      at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by TomYOON** [comment]
solved
/:id 경로가 /logout 경로를 인식해서 순서가 맞지않는 로직이 생겨 발생했음
